ProjectDate/ProjectDate.WEB/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProjectDate.BLL.DTO;
using ProjectDate.BLL.Interfaces;
using ProjectDate.WEB.Models.EmployeeViewModels;
using ProjectDate.WEB.Models.PositionViewModels;
using ProjectDate.WEB.Models.ProjectViewModels;

namespace ProjectDate.WEB.Controllers
{
    public class EmployeeController : Controller
    {
        private IEmployeeService employeeService;
        private IPositionService positionService;
        

        public EmployeeController(IEmployeeService employeeService, IPositionService positionService)
        {
            this.employeeService = employeeService;
            this.positionService = positionService;
        }

        public IActionResult Index()
        {
            IEnumerable<EmployeeDto> employeesDto = employeeService.GetAll();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<EmployeeDto, EmployeeViewModel>()).CreateMapper();
            var employees = mapper.Map<IEnumerable<EmployeeDto>, List<EmployeeViewModel>>(employeesDto);
            return View(employees);
        }

        public IActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public IActionResult Create(EmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                EmployeeDto employee = Mapper.Map<EmployeeDto>(model);
                employeeService.Create(employee);
                return RedirectToAction("Index");
            }

            return View();
        }

        public string SelectMember(int? projectId)
        {
            IEnumerable<EmployeeDto> employeesDto = employeeService.GetMember(projectId);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<EmployeeDto, EmployeeViewModel>()).CreateMapper();
            var employees = mapper.Map<IEnumerable<EmployeeDto>, List<EmployeeViewModel>>(employeesDto);
            string json = JsonConvert.SerializeObject(employees);
            return JsonConvert.SerializeObject(json,
                new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
        }

        public IActionResult Delete(int id)
        {
            employeeService.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult Update(int employeeId)
        {
            var employee = employeeService.Get(employeeId);
            EmployeeViewModel model = Mapper.Map<EmployeeViewModel>(employee);
            return PartialView(model);
        }

        [HttpPost]
        public IActionResult Update(EmployeeViewModel model)
        {
            var employee = Mapper.Map<EmployeeDto>(model);
            employeeService.Update(employee);
            return RedirectToAction("Index");
        }
    }
}

ProjectDate/ProjectDate.WEB/Controllers/PositionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProjectDate.BLL.DTO;
using ProjectDate.BLL.Interfaces;
using ProjectDate.WEB.Models.EmployeeViewModels;
using ProjectDate.WEB.Models.PositionViewModels;

namespace ProjectDate.WEB.Controllers
{
    public class PositionController : Controller
    {
        private IPositionService positionService;

        public PositionController(IPositionService positionService)
        {
            this.positionService = positionService;
        }

        public IActionResult Index()
        {
            IEnumerable<PositionDto> positionDtos = positionService.GetAll();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<PositionDto, PositionViewModel>()).CreateMapper();
            var positions = mapper.Map<IEnumerable<PositionDto>, List<PositionViewModel>>(positionDtos);
            return View(positions);
        }

        public IActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public IActionResult Create(PositionViewModel model)
        {
            if (ModelState.IsValid)
            {
                PositionDto position = Mapper.Map<PositionDto>(model);
                positionService.Create(position);
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            positionService.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult Update(int positionId)
        {
            var position = positionService.Get(positionId);
            PositionViewModel model = Mapper.Map<PositionViewModel>(position);
            return PartialView(model);
        }

        [HttpPost]
        public IActionResult Update(PositionViewModel model)
        {
            var position = Mapper.Map<PositionDto>(model);
            positionService.Update(position);
            return RedirectToAction("Index");
        }
    }
}

ProjectDate/ProjectDate.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectDate.WEB</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Проекты</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Employee" asp-action="Index">Сотрудники</a></li>
                    <li><a asp-area="" asp-controller="Position" asp-action="Index">Должности</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ProjectDate.WEB</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>